export default class sampleData {
	getSampleData() {
		return [
			{
				nombreSeccion: 'Octubre · 2022',
				class: 'slds-button slds-section__title-action',
				iconName: 'utility:date_input',
				items: [
					{
						id: '20',
						objectApiName: 'EmailMessage',
						titulo: 'Re: Mobile conversation on Monday with the new global team',
						subtitulo: 'You emailed Lea Chan',
						iconName: 'standard:email',
						clases: 'slds-timeline__item_expandable slds-timeline__item_email',
						fecha: '3/24/17 | 10:00',
						campo1Label: 'From',
						campo1Valor: 'Jackie Dewar',
						campo2Label: 'To',
						campo2Valor: 'Lea Chan',
						campo3Label: 'Email Body',
						campo3Valor: 'Hi everyone, Thanks for meeting with the team today and going through the proposals we saw. This goes on and wraps if needed.',
						campo3TextArea: true,
						visible: true
					},
					{
						id: '10',
						objectApiName: 'Task',
						titulo: 'Review proposals for EBC deck with larger team and have marketing review this',
						subtitulo: 'You created a task with Charlie Gomez',
						iconName: 'standard:task',
						clases: 'slds-timeline__item_expandable slds-timeline__item_task',
						fecha: '3/20/17 | 9:00',
						campo1Label: 'Name',
						campo1Valor: 'Charlie Gomez',
						campo2Label: 'Related To',
						campo2Valor: 'Tesla Cloudhub + Anypoint Connectors',
						campo3Label: 'Description',
						campo3Valor: 'Need to finalize proposals and brand details before the meeting',
						campo3TextArea: false,
						visible: true
					},
					{
						id: 'a0K7Q000001QmJrUAK',
						objectApiName: 'crm_Llamada__c',
						titulo: 'Mobile conversation on Monday',
						subtitulo: 'You logged a call with Adam Chan',
						iconName: 'standard:log_a_call',
						clases: 'slds-timeline__item_expandable slds-timeline__item_call',
						fecha: '3/23/17 | 10:00',
						campo1Label: 'Name',
						campo1Valor: 'Adam Chan',
						campo2Label: 'Related To',
						campo2Valor: 'Tesla Cloudhub + Anypoint Connectors',
						campo3Label: 'Description',
						campo3Valor: 'Adam seemed interested in closing this deal quickly! Let\'s move',
						campo3TextArea: false,
						visible: true
					},
					{
						id: '30',
						objectApiName: 'EmailMessage',
						titulo: 'Re: Mobile conversation on Monday with the new global team',
						subtitulo: 'You emailed Lea Chan',
						iconName: 'standard:email',
						clases: 'slds-timeline__item_expandable slds-timeline__item_email',
						fecha: '3/24/17 | 10:00',
						campo1Label: 'From',
						campo1Valor: 'Jackie Dewar',
						campo2Label: 'To',
						campo2Valor: 'Lea Chan',
						campo3Label: 'Email Body',
						campo3Valor: 'Hi everyone, Thanks for meeting with the team today and going through the proposals we saw. This goes on and wraps if needed.',
						campo3TextArea: true,
						visible: true
					},
					{
						id: '40',
						objectApiName: 'MessagingSession',
						titulo: 'Conversación de Whatsapp',
						subtitulo: 'You created an event withAida Lee and 5 others',
						iconName: 'standard:messaging_session',
						clases: 'slds-timeline__item_expandable slds-timeline__item_call',
						fecha: '3/24/17 | 10:30',
						campo1Label: 'Location',
						campo1Valor: 'Westen St. Francis, San Francisco, CA, 94622',
						campo2Label: 'Attendees',
						campo2Valor: 'Jason Dewar (Organizer) + 5 others',
						campo3Label: 'Description',
						campo3Valor: 'Let\'s discuss the 2017 product roadmap and address any questions',
						campo3TextArea: false,
						visible: true
					},
					{
						id: '50',
						objectApiName: 'Event',
						titulo: 'EBC Follow up call',
						subtitulo: 'You created an event withAida Lee and 5 others',
						iconName: 'standard:event',
						clases: 'slds-timeline__item_expandable slds-timeline__item_event',
						fecha: '3/24/17 | 10:30',
						campo1Label: 'Location',
						campo1Valor: 'Westen St. Francis, San Francisco, CA, 94622',
						campo2Label: 'Attendees',
						campo2Valor: 'Jason Dewar (Organizer) + 5 others',
						campo3Label: 'Description',
						campo3Valor: 'Let\'s discuss the 2017 product roadmap and address any questions',
						campo3TextArea: false,
						visible: true
					}
				]
			},
			{
				nombreSeccion: 'Septiembre · 2022',
				class: 'slds-button slds-section__title-action',
				iconName: 'utility:date_input',
				items: [
					{
						id: '60',
						objectApiName: 'Task',
						titulo: 'Review proposals for EBC deck with larger team and have marketing review this',
						subtitulo: 'You created a task with Charlie Gomez',
						iconName: 'standard:task',
						clases: 'slds-timeline__item_expandable slds-timeline__item_task',
						fecha: '3/20/17 | 9:00',
						campo1Label: 'Name',
						campo1Valor: 'Charlie Gomez',
						campo2Label: 'Related To',
						campo2Valor: 'Tesla Cloudhub + Anypoint Connectors',
						campo3Label: 'Description',
						campo3Valor: 'Need to finalize proposals and brand details before the meeting',
						campo3TextArea: false,
						visible: true
					},
					{
						id: '70',
						objectApiName: 'LiveChatTranscript',
						titulo: 'Re: Mobile conversation on Monday with the new global team',
						subtitulo: 'You emailed Lea Chan',
						iconName: 'standard:live_chat',
						clases: 'slds-timeline__item_expandable slds-timeline__item_event',
						fecha: '3/24/17 | 10:00',
						campo1Label: 'From',
						campo1Valor: 'Jackie Dewar',
						campo2Label: 'To',
						campo2Valor: 'Lea Chan',
						campo3Label: 'Email Body',
						campo3Valor: 'Hi everyone, Thanks for meeting with the team today and going through the proposals we saw. This goes on and wraps if needed.',
						campo3TextArea: false,
						visible: true
					},
					{
						id: '80',
						objectApiName: 'EmailMessage',
						titulo: 'Re: Mobile conversation on Monday with the new global team',
						subtitulo: 'You emailed Lea Chan',
						iconName: 'standard:email',
						clases: 'slds-timeline__item_expandable slds-timeline__item_email',
						fecha: '3/24/17 | 10:00',
						campo1Label: 'From',
						campo1Valor: 'Jackie Dewar',
						campo2Label: 'To',
						campo2Valor: 'Lea Chan',
						campo3Label: 'Email Body',
						campo3Valor: 'Hi everyone, Thanks for meeting with the team today and going through the proposals we saw. This goes on and wraps if needed.',
						campo3TextArea: true,
						visible: true
					},
					{
						id: '90',
						objectApiName: 'Event',
						titulo: 'EBC Follow up call',
						subtitulo: 'You created an event withAida Lee and 5 others',
						iconName: 'standard:event',
						clases: 'slds-timeline__item_expandable slds-timeline__item_event',
						fecha: '3/24/17 | 10:30',
						campo1Label: 'Location',
						campo1Valor: 'Westen St. Francis, San Francisco, CA, 94622',
						campo2Label: 'Attendees',
						campo2Valor: 'Jason Dewar (Organizer) + 5 others',
						campo3Label: 'Description',
						campo3Valor: 'Let\'s discuss the 2017 product roadmap and address any questions',
						campo3TextArea: false,
						visible: true
					}
				]
			},
			{
				nombreSeccion: 'Mayo · 2022',
				class: 'slds-button slds-section__title-action',
				iconName: 'utility:date_input',
				items: [
					{
						id: '100',
						objectApiName: 'Task',
						titulo: 'Review proposals for EBC deck with larger team and have marketing review this',
						subtitulo: 'You created a task with Charlie Gomez',
						iconName: 'standard:task',
						clases: 'slds-timeline__item_expandable slds-timeline__item_task',
						campo1Label: 'Name',
						campo1Valor: 'Charlie Gomez',
						campo2Label: 'Related To',
						campo2Valor: 'Tesla Cloudhub + Anypoint Connectors',
						campo3Label: 'Description',
						campo3Valor: 'Need to finalize proposals and brand details before the meeting',
						campo3TextArea: false,
						visible: true
					},
					{
						id: '110',
						objectApiName: 'Event',
						titulo: 'EBC Follow up call',
						subtitulo: 'You created an event withAida Lee and 5 others',
						iconName: 'standard:event',
						clases: 'slds-timeline__item_expandable slds-timeline__item_event',
						fecha: '3/24/17 | 10:30',
						campo1Label: 'Location',
						campo1Valor: 'Westen St. Francis, San Francisco, CA, 94622',
						campo2Label: 'Attendees',
						campo2Valor: 'Jason Dewar (Organizer) + 5 others',
						campo3Label: 'Description',
						campo3Valor: 'Let\'s discuss the 2017 product roadmap and address any questions',
						campo3TextArea: false,
						visible: true
					}
				]
			}
		];
	}
}