import { createElement } from '@lwc/engine-dom';
import Csbd_test_cgpta from 'c/csbd_test_cgpta';

describe('c-csbd-test-cgpta', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-csbd-test-cgpta', {
            is: Csbd_test_cgpta
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});