import {createElement} from 'lwc';
import Csbd_ChatOperativas from 'c/csbd_ChatOperativas';

describe('c-csbd-chat-operativas', () => {
	afterEach(() => {
		//The jsdom instance is shared across test cases in a single file so reset the DOM
		while (document.body.firstChild) {
			document.body.removeChild(document.body.firstChild);
		}
	});

	it('TODO: test case generated by CLI command, please fill in test logic', () => {
		//Arrange
		const element = createElement('c-csbd-chat-operativas', {
			is: Csbd_ChatOperativas
		});

		//Act
		document.body.appendChild(element);

		//Assert
		//const div = element.shadowRoot.querySelector('div');
		expect(1).toBe(1);
	});
});