public with sharing class CC_Llamada_Input {

    public String usuario {get;set;}
    public String extension {get;set;}
    public String connId {get;set;}
    public String transferConnId {get;set;}
    public String ani {get;set;}
    public String dnis {get;set;}
    public String servicio {get;set;}
    public String asunto {get;set;}
    public String numPerso {get;set;}
    public String idioma {get;set;}
    public String datos {get;set;}
    public String connIdCognitivo {get;set;}
    public String llamadaId {get;set;}
    public String casoId {get;set;}
    public String salesforceParentId {get;set;}
    public String canalEmpleado {get;set;}
    public String cognitivoId {get;set;}
    public String empleadoId {get;set;}
    public String empleadoTelefono {get;set;}
    public String negocio {get;set;}
    public String nombreCampana {get;set;}
    public String statusAuto {get;set;}
    public String perfil {get;set;}
    public String urlGrabacion {get;set;}
    public String sentiment {get;set;}
    public String summary {get;set;}
    public String assistantResponse {get;set;}
    public String userQuery {get;set;}
    public String telefonoUnico {get;set;}
    public String vRUDoc {get;set;}
}